[package]
name = "action_tests"
edition = "2024.beta"

[dependencies]
AccountProtocol = { local = "../move-framework/packages/protocol" }
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }
futarchy_markets_primitives = { local = "../futarchy_markets_primitives" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_operations = { local = "../futarchy_markets_operations" }
futarchy_oracle = { local = "../futarchy_oracle_actions" }
futarchy_actions = { local = "../futarchy_actions" }
futarchy_factory = { local = "../futarchy_factory" }
futarchy_governance_actions = { local = "../futarchy_governance_actions" }

[addresses]
action_tests = "0x0"
futarchy_types = "0x0515629b4b7ca29785fb472fae4c2778fc38f2bfa4da79e2bc25362d8dbe5b7c"
futarchy_one_shot_utils = "0x28c9d47b9267a0012fd403de63ffba1c5f3a65b447c5b80da3df277feadfb6db"
futarchy_core = "0xc67984870e65323982233f9859797b9ef899de98160e5736646923d04dff01fa"
futarchy_markets_primitives = "0x186dc94eea918d13ed8058ffee05e9ebb81eaf4bfdf1a64bf01835cb9a5ca1aa"
futarchy_markets_core = "0xed8a69780ec1ed19a227d5bce366755f24c34e5495948245216df6a07a6dc45b"
futarchy_markets_operations = "0x56fc1a26a4bcbe4e1755f48e6be74c970a05458916eb124f3182430c10c3e728"
futarchy_oracle = "0xbb610760ac4dc51c8e886d1d881f63d766fe62a94dea06775d3dbc28d2579b25"
futarchy_actions = "0xd8307d1de8374b55a2180fbc87087209cacfe3795ecd44782324955b01bb962b"
futarchy_factory = "0xd181b5b276c9c669b42fc87e5b0b49e120a4ce375a58ef5d583d4548c50357b5"
futarchy_governance_actions = "0x357d13c6219461736559b071f16785aad0aa7759d772dea037d08668792de0cf"
account_protocol = "0xc318615056aa8aca8aab1312c1e3604aab3aff0f0e2a7a7824fe2646f91d6381"
account_actions = "0x187eeffedb81b4802817e3f0387ca736303fb9d80f4d42e5f966f3c202cfdcc3"
