[package]
name = "AccountProtocol"
edition = "2024"
license = "Apache-2.0"
published-at = "0x0"
authors = [ "Thouny (thouny@tuta.io)", "Greshamscode" ]

[dependencies]

[addresses]
account_protocol = "0x41ba0ee7ae07bb80e22128f6daeed1d765289d88d6919fa412b544f05a967b9d"
