[package]
name = "AccountProtocol"
edition = "2024"
license = "Apache-2.0"
authors = [ "Thouny (thouny@tuta.io)", "Greshamscode" ]

[dependencies]

[addresses]
account_protocol = "0xd1c96f57e175a85a01252a6c64426be6beb2e0a5b47ac15c9e84428d5d6a0216"
