[package]
name = "AccountProtocol"
edition = "2024"
license = "Apache-2.0"
authors = [ "Thouny (thouny@tuta.io)", "Greshamscode" ]

[dependencies]

[addresses]
account_protocol = "0x2fbef131639a2febdd72814533faff704b8d42b1c1f37cd4a27ad725a4e6eff3"
