[package]
name = "AccountActions"
edition = "2024"
license = "Apache-2.0"
authors = [ "Thouny (thouny@tuta.io)", "Greshamscode" ]

[dependencies]
AccountProtocol = { local = "../protocol" }

[addresses]
account_actions = "0x1e04afce2c728679d58d32fbb44063eb0d85fbba1d9e75976d800e3b325beee2"
account_protocol = "0xe026bb03c035570d73c33c550a00a8d626074f533d78872c13cb5da8b827a839"
