[package]
name = "AccountActions"
edition = "2024"
license = "Apache-2.0"
authors = [ "Thouny (thouny@tuta.io)", "Greshamscode" ]

[dependencies]
AccountProtocol = { local = "../protocol" }

[addresses]
account_actions = "0x500099eef12683a43760ce0b486fe948bd2d6fbb5a6a9fc0a2ac09a8b73b067e"
account_protocol = "0x2fbef131639a2febdd72814533faff704b8d42b1c1f37cd4a27ad725a4e6eff3"
