[package]
name = "AccountActions"
edition = "2024"
license = "Apache-2.0"
authors = [ "Thouny (thouny@tuta.io)", "Greshamscode" ]

[dependencies]
AccountProtocol = { local = "../protocol" }

[addresses]
account_actions = "0xa467239838009b2e941a1ccfa2c8ffe72663a0a01c71ea9b1f26b0a8ff4426b3"
account_protocol = "0x54d93527a2e54cc8d7a5012496eb0080d1d373b8a4ba05fd2637d21ed5bd29ae"
