[package]
name = "AccountActions"
edition = "2024"
license = "Apache-2.0"
authors = [ "Thouny (thouny@tuta.io)", "Greshamscode" ]

[dependencies]
AccountProtocol = { local = "../protocol" }

[addresses]
account_actions = "0x5bce7c8f861d82d3db48bec88fdfc3e831a143d94906b3247d2a34afd37a5028"
account_protocol = "0xf352aca569e09c6af686d88a5832e59737f185ae7e7ab649550bc819107f3b1d"
