[package]
name = "futarchy_oracle"
edition = "2024.beta"
published-at  = "0x0"

[dependencies]
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_operations = { local = "../futarchy_markets_operations" }
AccountProtocol = { local = "../move-framework/packages/protocol" }
[addresses]
futarchy_oracle = "0x0b686b0116374e6c5b775e6a6380ca7ef6be476ba09f21829d47e20af86716d2"
futarchy_types = "0xa06cb418b560633850b1f87cd427a39f07af1c90450fedf9eafc9dbe302175e8"
futarchy_one_shot_utils = "0x18bacc6c12bb87f6c2ea5048081d9ee0aa7e8307e727225593e2d1fe2ede93f5"
futarchy_core = "0xfc510a880a9264679b125916302f9f266694f544275d55eeec624b70a0eef4a8"
futarchy_markets_core = "0xf58542c51e2a32f6b09b5681242f90708d911cc3f101603d5436660cbb8c1eea"
futarchy_markets_operations = "0x9d65d3dc464706329b1d13484e6f754aa136da97dc83f8f8f91b970552f0a689"
account_protocol = "0x1af6547488aa54a85b7702c21e2bba46e122baf7aa2f9e57a18456fb21731fc9"
account_actions = "0xdc54c60d24003ce93b8fbc41c8cd8b92a41b9a82d4c1ed893a0eda57ea313eae"
