[package]
name = "futarchy_oracle"
edition = "2024.beta"
published-at  = "0x0"

[dependencies]
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_operations = { local = "../futarchy_markets_operations" }
AccountProtocol = { local = "../move-framework/packages/protocol" }
[addresses]
futarchy_oracle = "0x2f4c7890999d58bbfed3cb93d645194ae87aac75520711c6791949ab1e7f1861"
futarchy_types = "0x9e1997fb19963f75e300b863aa68eb785e7fe4f08a0bfd9c511d83d730f1297d"
futarchy_one_shot_utils = "0x9daeeb8e9250f8618c762f60424a84b6bd91ce5aa31e4d83c94ee364a9dc87dd"
futarchy_core = "0xf9769f89035828e9ed8fc6d4d9a0431a836c2aa64c55ccab545b33c2d9ba7a49"
futarchy_markets_core = "0x872c4474780d9274ada6e305681377266f6cf7d0d9822c0222f29ef3a336bd0f"
futarchy_markets_operations = "0xdbb5b5c3c48d9f677a6c611ab4088b10ed1ef3be4e9a261ab0ac32786fed7535"
account_protocol = "0x6503bcc7f9e1678938e80df33064b127e6c7d5eb26ee27e14fa872ed3a340af6"
account_actions = "0xcd0d462815be88b9d5405f9e0443fcdc1e83746fa5c2aeba0eac032306a0fb9d"
