[package]
name = "futarchy_oracle"
edition = "2024.beta"
published-at  = "0x0"

[dependencies]
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_operations = { local = "../futarchy_markets_operations" }
AccountProtocol = { local = "../move-framework/packages/protocol" }
[addresses]
futarchy_oracle = "0x2d1034df0e44fe7c759c15931abb0eb49baa1104cc7421e520578f1eff1fe8f7"
futarchy_types = "0x7dc0d3a6d8eba969d853834c3b4d5c6be36b7a78fbc263ac22f3ba580cb22e0e"
futarchy_one_shot_utils = "0x0c9c44770746a6bdc70bbc20545a679c048e2d7f8bf4e3c63fce760d7eda9a4d"
futarchy_core = "0xd3c702a45d35c25a4491ee66ed7177b7c4dfe9ddfa62ccaa003c4715c398b546"
futarchy_markets_core = "0x88d414f05a9cbfe24c2f8eab213ce3d552761424f5d73ae6df84d1d83cf56fcf"
futarchy_markets_operations = "0xd45f9f77e71954038636f46a184310c66e9d983f7aad47e22243480c22c10390"
account_protocol = "0x41ba0ee7ae07bb80e22128f6daeed1d765289d88d6919fa412b544f05a967b9d"
