[package]
name = "futarchy_oracle"
edition = "2024.beta"
published-at  = "0x0"

[dependencies]
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_operations = { local = "../futarchy_markets_operations" }
AccountProtocol = { local = "../move-framework/packages/protocol" }
[addresses]
futarchy_oracle = "0xa85e1a1666f45c3ef386a3e02df003a13c1f4022f578a45dfb611fe8f58efaa4"
futarchy_types = "0x3eb6e819f066b5496b793d4e4cdc89efd547e526b895a1d30ffbab46825b9228"
futarchy_one_shot_utils = "0x6f61bf04135b3a5c2f5868e35613c26f2d99bc1c35679591be69a507535b91f2"
futarchy_core = "0xd633a97440c4f1bbf5957b931b2c556d0fabf7a53c9ed447b57f009150c9647d"
futarchy_markets_core = "0xcc80f13e07bc60612bd0ec7d64e11ab70f98ceb44767e90a03f9b8383ede8a5f"
futarchy_markets_operations = "0xe25ae2f527aeb80977799c42c4f36eedb443cf47e4cc5f134da2fb2ee4183213"
account_protocol = "0x9dad524c13bef3723e437afa147bab861d2dea174194f660a2be629688db4e21"
account_actions = "0xb646f2d035b86e24eb15b4ff5cf853cb3eb34876bee36e6d6b03b69913592917"
