[package]
name = "futarchy_oracle"
edition = "2024.beta"
published-at  = "0x0"

[dependencies]
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_operations = { local = "../futarchy_markets_operations" }
AccountProtocol = { local = "../move-framework/packages/protocol" }
[addresses]
futarchy_oracle = "0x93ccc1fbfa04e8d6ad17a08f45237c32a1caa0db228e6ac4d140bc1c008c2715"
futarchy_types = "0xbbd1acdf01c5c703191e0332ff26dde4e6f5190c067ee13c1b7ae33dfefafe63"
futarchy_one_shot_utils = "0x4112eceed4a46cb27a74c60004e52992fe8d0a7cf0b5ffdf0be4ffa8147e1fdd"
futarchy_core = "0xd05dbb99121693a5b24b9eacbc627bf4de7cbefcb7fda82ed0ccda26cc3e1fa4"
futarchy_markets_core = "0xdb574fe23c2ef2fadd3027b7e3651257e87fa9a9d2940a28c9f6d304b80671f6"
futarchy_markets_operations = "0x13c5f80df4d3383311f0a26a47be2e2d35989bd6c4aef0e1531a3d766ea0a543"
account_protocol = "0x46a6b374fdb33f027240337bfaf9c5224b982cc71d4a513013c5ab0e85f1b2f3"
account_actions = "0x24e8af1be1910779c682e4fa9ba284adc05a6c4bf28680657d73d0031ca40df0"
