[package]
name = "futarchy_governance"
edition = "2024.beta"
published-at = "0x0"

[dependencies]
AccountProtocol = { local = "../move-framework/packages/protocol" }
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }
futarchy_markets_primitives = { local = "../futarchy_markets_primitives" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_operations = { local = "../futarchy_markets_operations" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_actions = { local = "../futarchy_actions" }
futarchy_governance_actions = { local = "../futarchy_governance_actions" }

[addresses]
futarchy_governance = "0xd6bf372ba2cd3f78bef8788a8f7c669877b7c2578c98f2dcb1417f3effc2d7d8"
futarchy_types = "0xbb37dff8691a336889f1f47c7fe525760f5360868b92fb3bdfed6da9138dacb5"
futarchy_core = "0x930527ed7d768330586037eea7f377e23276d30481f94d4745e19cf012e96d6f"
futarchy_markets_primitives = "0x8bac6193f3ef246fc357a297a051e15cb39f60f393c8ef9e83d807883586a62f"
futarchy_markets_core = "0x4d46e4803266ffa3c650d76c2fd176853a96261e60d55038d63ce4b57bb55a1d"
futarchy_markets_operations = "0x993e4dd786e6f1deeff860d88239e26311cddddc54d3ce7056df86d48c8e300e"
futarchy_one_shot_utils = "0xc803dc889d4c5a15c68e502205807a25f679244bd85e1a6b616fd72230e2e93a"
futarchy_actions = "0x98b76336b70255fcd16c246e2baad0a9d97b02461d110fd36eb65a09448b19c8"
futarchy_governance_actions = "0xe11799be747c64f888723202dab96b4478e3852cfde8c2b56797f22dbe89d9a4"
account_protocol = "0x9f217b13ac20ac380c1ead8c9f8b7f569ff8b40940c2d6e7feb5ae2de9689eb5"
account_actions = "0x1f99fdb0e165cfd49e145e03c6398a145c322c6f1d94c5daf3a30f4badd08e25"
