[package]
name = "futarchy_governance"
edition = "2024.beta"
published-at = "0x0"

[dependencies]
AccountProtocol = { local = "../move-framework/packages/protocol" }
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }
futarchy_markets_primitives = { local = "../futarchy_markets_primitives" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_operations = { local = "../futarchy_markets_operations" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_actions = { local = "../futarchy_actions" }
futarchy_governance_actions = { local = "../futarchy_governance_actions" }

[addresses]
futarchy_governance = "0xab2f7eb81040919febdb71c1721bdc7e761344dca8b409b6333489644f91b4a9"
futarchy_types = "0x892bcd3ca6e77a9f1e91cec843695b17ec5081626761f9f2aa581da4440a2565"
futarchy_core = "0x1ecae2a477838976a5299376814f0886bdaa66cf04d6f223ff4b33bed3d8b3a2"
futarchy_markets_primitives = "0xda6e60b79cb7b56acc542726447ab9370429d815a703d3ec4fb5d64de4240e2e"
futarchy_markets_core = "0xb10f4ecca3f60a0de6734f870cebe10781c4a446068c00ede2bc15142f0766a0"
futarchy_markets_operations = "0xbe005d8019c43b9c0e49a29c18d463333f398a76e963d9ad675b7eb4d912a3c3"
futarchy_one_shot_utils = "0x951b41505eb6fb53060d879ff274280c5e73c0d68006c5a2725db2c442704492"
futarchy_actions = "0x34d0615b66c63d211c92e45b6ed8a14b633500b4cb6dacb422b8bb99b7f45d14"
futarchy_governance_actions = "0xb5a510874e09393d64b2034cb911ed00467417686d64996d471a2f431cbda254"
account_protocol = "0xf199aecf42ba7372e521d7a7e328ab79eb1103c1879b3ebc846ea2e852d2f605"
account_actions = "0x9c511e03f6e2df2872464f0f64e79bab38c86b13866cf1d304d067b444334e05"
