[package]
name = "futarchy_governance"
edition = "2024.beta"
published-at = "0x0"

[dependencies]
AccountProtocol = { local = "../move-framework/packages/protocol" }
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }
futarchy_markets_primitives = { local = "../futarchy_markets_primitives" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_operations = { local = "../futarchy_markets_operations" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_actions = { local = "../futarchy_actions" }
futarchy_governance_actions = { local = "../futarchy_governance_actions" }

[addresses]
futarchy_governance = "0x1d78660ddd10ab414043986d541e39d82dd38371a6c8e4c3a9f52a0b63763caa"
futarchy_types = "0xa06cb418b560633850b1f87cd427a39f07af1c90450fedf9eafc9dbe302175e8"
futarchy_core = "0xfc510a880a9264679b125916302f9f266694f544275d55eeec624b70a0eef4a8"
futarchy_markets_primitives = "0x94a46e6eabf16df7c51fbf2f88486d20859df0d71a46a482c61c75c485792cf8"
futarchy_markets_core = "0xf58542c51e2a32f6b09b5681242f90708d911cc3f101603d5436660cbb8c1eea"
futarchy_markets_operations = "0x9d65d3dc464706329b1d13484e6f754aa136da97dc83f8f8f91b970552f0a689"
futarchy_one_shot_utils = "0x18bacc6c12bb87f6c2ea5048081d9ee0aa7e8307e727225593e2d1fe2ede93f5"
futarchy_actions = "0x4612355286952fd4bca0c58b2f60282e43f745a7a4c6c979ced8c260f750c76c"
futarchy_governance_actions = "0xdf65af5860d65292a5ddce4ead9c6d110cd148e7d0de6988ea2337fc5d99c5eb"
account_protocol = "0x1af6547488aa54a85b7702c21e2bba46e122baf7aa2f9e57a18456fb21731fc9"
account_actions = "0xdc54c60d24003ce93b8fbc41c8cd8b92a41b9a82d4c1ed893a0eda57ea313eae"
