[package]
name = "futarchy_governance"
edition = "2024.beta"
published-at = "0x0"

[dependencies]
AccountProtocol = { local = "../move-framework/packages/protocol" }
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }
futarchy_markets_primitives = { local = "../futarchy_markets_primitives" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_operations = { local = "../futarchy_markets_operations" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_actions = { local = "../futarchy_actions" }
futarchy_governance_actions = { local = "../futarchy_governance_actions" }

[addresses]
futarchy_governance = "0x5446a57b9974064c8f070f3b130870781eb9ebe24732e5c89bcbf63bce30654b"
futarchy_types = "0x7dc0d3a6d8eba969d853834c3b4d5c6be36b7a78fbc263ac22f3ba580cb22e0e"
futarchy_core = "0xd3c702a45d35c25a4491ee66ed7177b7c4dfe9ddfa62ccaa003c4715c398b546"
futarchy_markets_primitives = "0xf8d24d22f6c31a0bfd5b5a7ca6f0a6172682448bf6b459ec7daed057fddccd0c"
futarchy_markets_core = "0x88d414f05a9cbfe24c2f8eab213ce3d552761424f5d73ae6df84d1d83cf56fcf"
futarchy_markets_operations = "0xd45f9f77e71954038636f46a184310c66e9d983f7aad47e22243480c22c10390"
futarchy_one_shot_utils = "0x0c9c44770746a6bdc70bbc20545a679c048e2d7f8bf4e3c63fce760d7eda9a4d"
futarchy_actions = "0x9a4ed709bfa0c0229021ac4ef946c6b0cfa109e26e825e66783b50daa38286e4"
futarchy_governance_actions = "0xbd90a07ee69eeff8a2715dd5d7f070cc560627fa1bf30f6e78bee76ee3be3a4b"
account_protocol = "0x41ba0ee7ae07bb80e22128f6daeed1d765289d88d6919fa412b544f05a967b9d"
account_actions = "0x75c59ba5279bd1c4e9a3be412ace1839ed17125301c320cabb04616c910f87f8"
