[package]
name = "futarchy_governance"
edition = "2024.beta"
published-at = "0x0"

[dependencies]
AccountProtocol = { local = "../move-framework/packages/protocol" }
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }
futarchy_markets_primitives = { local = "../futarchy_markets_primitives" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_operations = { local = "../futarchy_markets_operations" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_actions = { local = "../futarchy_actions" }
futarchy_governance_actions = { local = "../futarchy_governance_actions" }

[addresses]
futarchy_governance = "0x0f20e8aa458829ca1cf1d16fb3094e707117b33c2e3c170463253e28e8094cd7"
futarchy_types = "0x3eb6e819f066b5496b793d4e4cdc89efd547e526b895a1d30ffbab46825b9228"
futarchy_core = "0xd633a97440c4f1bbf5957b931b2c556d0fabf7a53c9ed447b57f009150c9647d"
futarchy_markets_primitives = "0x98f85b330101a8f382f9465f43499d31e6d21caa05ff9cc6c9b46387fc47ee8f"
futarchy_markets_core = "0xcc80f13e07bc60612bd0ec7d64e11ab70f98ceb44767e90a03f9b8383ede8a5f"
futarchy_markets_operations = "0xe25ae2f527aeb80977799c42c4f36eedb443cf47e4cc5f134da2fb2ee4183213"
futarchy_one_shot_utils = "0x6f61bf04135b3a5c2f5868e35613c26f2d99bc1c35679591be69a507535b91f2"
futarchy_actions = "0x4072b118078e3244f29a6846310500ffbf7798ae1aa5f9ec3df37dd8eb584045"
futarchy_governance_actions = "0x98fb6ffc3b9b97de6a108a5ae3ab3921693170d35bc8d7f53005ed6662107782"
account_protocol = "0x9dad524c13bef3723e437afa147bab861d2dea174194f660a2be629688db4e21"
account_actions = "0xb646f2d035b86e24eb15b4ff5cf853cb3eb34876bee36e6d6b03b69913592917"
