[package]
name = "futarchy_governance"
edition = "2024.beta"
published-at = "0x0"

[dependencies]
AccountProtocol = { local = "../move-framework/packages/protocol" }
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }
futarchy_markets_primitives = { local = "../futarchy_markets_primitives" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_operations = { local = "../futarchy_markets_operations" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_actions = { local = "../futarchy_actions" }
futarchy_governance_actions = { local = "../futarchy_governance_actions" }

[addresses]
futarchy_governance = "0x4924a2c2b5012c3804d162d04bf887c7cd1226802292e03390fda0d279148e37"
futarchy_types = "0xdc003c60cdcb419a27622342a30bd5b0058f75f7264e119842a719ac58fc4cc0"
futarchy_core = "0xfbfa12feb10f6d525d6b8703dad4b552c8b0d0ab973dc8552bde6fd086080fd2"
futarchy_markets_primitives = "0x5d2f30aa5c62f3c10f433d7859d9ca7e2683505fc93b9600e9c5d7bd68217a54"
futarchy_markets_core = "0x76f5ce653d3df051c780003576b9fbab19be5fb689474f8bfc37e56ea1cd6cd5"
futarchy_markets_operations = "0xa0189ab2ea14793f4e5d9fbe6f39de6aa7e2b34876a13986dacd8d615ee1be17"
futarchy_one_shot_utils = "0xa799a5c4d25058948541517d899c951f195c64b5a8d26360fe14f407e4534028"
futarchy_actions = "0x04db3ae0019a91ecffb664a9caa6505717a1a74d7573787e611aa0261c774f2f"
futarchy_governance_actions = "0x873eaca2e92db8e5490c9863e168023a7a8bc8df0243ada9fa27212b98cf928e"
account_protocol = "0xb0d09d6cdd4fc923edd080356460a0c6b481a6aac3cadc968629a5292d3f1c12"
account_actions = "0xad8b55859a7c3a288c252c472c564db78aa92076fcfe0458f69dd14429bbc4de"
