[package]
name = "futarchy_markets_core"
edition = "2024"
license = "BSL"

[dependencies]
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_markets_primitives = { local = "../futarchy_markets_primitives" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }

[addresses]
futarchy_markets_core = "0xa8448615cbe5c62a931ccaf2634750f58b31de079e23e5eccb1d5663cc39469f"
futarchy_markets_primitives = "0x30b540d5e013c613d7d01c9ee43800358afd7866b98672edce334a3cedee4981"
futarchy_types = "0x80ecc04c6374cb318c4166b3a2802d45d31a82773f82e8533a8eedb943d8681f"
futarchy_one_shot_utils = "0x40c68c25eedceca27bfdf3bb5e25300c3c1d75ec3c8eff809e896d38e5c2aa1b"
futarchy_core = "0xcf84743109ec866c41e9659efc1c1b14582cc566255054455c97cd9d98e6bd0d"
