[package]
name = "futarchy_markets_operations"
edition = "2024"
license = "BSL"

[dependencies]
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_primitives = { local = "../futarchy_markets_primitives" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }

[addresses]
futarchy_markets_operations = "0xbe005d8019c43b9c0e49a29c18d463333f398a76e963d9ad675b7eb4d912a3c3"
futarchy_markets_core = "0xb10f4ecca3f60a0de6734f870cebe10781c4a446068c00ede2bc15142f0766a0"
futarchy_markets_primitives = "0xda6e60b79cb7b56acc542726447ab9370429d815a703d3ec4fb5d64de4240e2e"
futarchy_types = "0x892bcd3ca6e77a9f1e91cec843695b17ec5081626761f9f2aa581da4440a2565"
futarchy_one_shot_utils = "0x951b41505eb6fb53060d879ff274280c5e73c0d68006c5a2725db2c442704492"
futarchy_core = "0x1ecae2a477838976a5299376814f0886bdaa66cf04d6f223ff4b33bed3d8b3a2"
