[package]
name = "futarchy_markets_operations"
edition = "2024"
license = "BSL"

[dependencies]
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_primitives = { local = "../futarchy_markets_primitives" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }

[addresses]
futarchy_markets_operations = "0x78ecb6899ed126e03cc3b70e0470d85ab44bb873984738abdff35f488c2cc648"
futarchy_markets_core = "0x549766068b12305e23b08df5d0a3215b838d389d265869cf8209b5b9a899decd"
futarchy_markets_primitives = "0x8627076c53d010c940ce550d602b5179e3ddd893ac8a8d57b2930926500e981f"
futarchy_types = "0x1d4d1616b1f71cfad98651322ad8c71882dcabbab70f7c2946838c7a51a222dc"
futarchy_one_shot_utils = "0xad0563997fe9aa2092ccea8fdb8765588040faff912f1e0a3a1df7f9b728c263"
futarchy_core = "0xcac9f0b7febc2dd004c976c193c88dc3f895a1c5517fe4ffc1e845f01fdb05b2"
