[package]
name = "futarchy_markets_operations"
edition = "2024"
license = "BSL"

[dependencies]
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_primitives = { local = "../futarchy_markets_primitives" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }

[addresses]
futarchy_markets_operations = "0x631fdabeb831d03f27389e63b8a0ba99b20910f8334158d88c26b56de46ea2cb"
futarchy_markets_core = "0xe6dd72eaa5d0c60152449f6a28f8dfa04cc412e1606bfbc76a89b54eb2633328"
futarchy_markets_primitives = "0x724a132d4d6c25cc197550d7317804f93e34b31c8094e3307ef46b71b7434197"
futarchy_types = "0xbdbdfdd75fab3265eb1857820f70105208d08fb77cbe80b55fe20209871e0fa1"
futarchy_one_shot_utils = "0x487c17c6778ed34664b02a3d74b43e4ebc06f8185398c4d8234344ea9a536a6b"
futarchy_core = "0x38e7547c0387dabdc8ee889ce91e9923b245a56b20437525e91f3b89e9ac4074"
