[package]
name = "futarchy_markets_operations"
edition = "2024"
license = "BSL"

[dependencies]
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_primitives = { local = "../futarchy_markets_primitives" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }

[addresses]
futarchy_markets_operations = "0x2fcdc43b419bf0819101f6419271566d0a4d9016c274322833a32593bc2cf42b"
futarchy_markets_core = "0x1407e4caf59c5e4ac9f26bd95e579459e80819cf9d52b002410aad288a350db0"
futarchy_markets_primitives = "0x6f040dab19a1bb9b79874bc184a184489745e9a659c3c900fbbc0f9f8466e7cc"
futarchy_types = "0x737bf776a35e6cfae5cf14ac69df956bb9a7652a4fad01b74dc86629ed06cec2"
futarchy_one_shot_utils = "0x4161cc12bee6bb45e266cb14dbf76f7b028ca109ae58d84d88ae86112d72253f"
futarchy_core = "0x27d5b9de627c3ee21c7327b8fbc4998a0d050afb736cc6144ec716df592cf9fe"
