[package]
name = "futarchy_actions"
edition = "2024.beta"
published-at  = "0x0"

[dependencies]
AccountProtocol = { local = "../move-framework/packages/protocol" }
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }
futarchy_markets_primitives = { local = "../futarchy_markets_primitives" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_operations = { local = "../futarchy_markets_operations" }
[addresses]
futarchy_actions = "0x22c0d5c1e413f8b7aee9a87004b83d238f46745dab02a0347aef7f94f58b959a"
futarchy_types = "0x1d4d1616b1f71cfad98651322ad8c71882dcabbab70f7c2946838c7a51a222dc"
futarchy_one_shot_utils = "0xad0563997fe9aa2092ccea8fdb8765588040faff912f1e0a3a1df7f9b728c263"
futarchy_core = "0xcac9f0b7febc2dd004c976c193c88dc3f895a1c5517fe4ffc1e845f01fdb05b2"
futarchy_markets_primitives = "0x8627076c53d010c940ce550d602b5179e3ddd893ac8a8d57b2930926500e981f"
futarchy_markets_core = "0x549766068b12305e23b08df5d0a3215b838d389d265869cf8209b5b9a899decd"
futarchy_markets_operations = "0x78ecb6899ed126e03cc3b70e0470d85ab44bb873984738abdff35f488c2cc648"
account_protocol = "0x21a723ea40eccdb1aace5b9bb2e58c30cb6043bad7457791b267e6bcd125edc3"
account_actions = "0x9201c7110b7e04bea4a7bde64b4348b901652015d42dbbd706a64cf21d329c55"
