[package]
name = "futarchy_actions"
edition = "2024.beta"
published-at  = "0x0"

[dependencies]
AccountProtocol = { local = "../move-framework/packages/protocol" }
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }
futarchy_markets_primitives = { local = "../futarchy_markets_primitives" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_operations = { local = "../futarchy_markets_operations" }
[addresses]
futarchy_actions = "0x6de19da17ae9a034b9e8be379def64a02c1c8b61aa22d87655782b2fe17c6cc2"
futarchy_types = "0x5d04f0ca7d9b593632accc6a24102e00f882b07181d0c708f5f4c431ceeb6673"
futarchy_one_shot_utils = "0x6467a6646bb8bba5b154459fc78d665bdfc8dda44db80c8ed83bc3c9f11ea876"
futarchy_core = "0x17142bdf59236ce3e66ea5dfe48364c7721a8c98ad7ce6ca881ca8d2054536a9"
futarchy_markets_primitives = "0x7d5fd668724d5452c79a63bebd8e474ea4ae4dba33d6cb8120a3f06939e3da9a"
futarchy_markets_core = "0x5b1b32cc8320229ef61a380ab1827008748befb9e8965e959115f71d3c33681f"
futarchy_markets_operations = "0x2265cb02754106fe05d719229d7ab90ee6b2d2708de26f84a030bafad0e54be5"
account_protocol = "0x08d48380e5f718897c60751361b993f8a76e36b856dda74c7cc7d25712f0c667"
account_actions = "0xdbd93c2c3238693a6217f29e8246c39c451f07e06e3fe7a46f2a3e614008623c"
