[package]
name = "futarchy_actions"
edition = "2024.beta"
published-at  = "0x0"

[dependencies]
AccountProtocol = { local = "../move-framework/packages/protocol" }
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }
futarchy_markets_primitives = { local = "../futarchy_markets_primitives" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_operations = { local = "../futarchy_markets_operations" }
[addresses]
futarchy_actions = "0x92f09151edfac26e3113840b3a442aedf58a9650576a8ba2321c37decf609b46"
futarchy_types = "0x2ac5fc1f66a3827cde88494b864485a99bca05e4207de4e03813a92771728f2d"
futarchy_one_shot_utils = "0x71a6037c0b7b8129f609bf75b59224543f404a1f2cee377524d5a9dc49d050c5"
futarchy_core = "0x6865d933e01b147628a62d34fbb90cbb48931e51cb7973a231cf64d77375d5c8"
futarchy_markets_primitives = "0x458ad6dacd0e73319897e4e9d16457dbf5be5093c7a257f1473c3d638a13dc70"
futarchy_markets_core = "0x520c8f2f0d0be3a841ebf2ec2c8bb92387cf54719072fc1394adfd551df3f060"
futarchy_markets_operations = "0xfe4b547cd4add7f250090898de77ddf875ea193877e4d0b2ff20338a70b29ce9"
account_protocol = "0xe026bb03c035570d73c33c550a00a8d626074f533d78872c13cb5da8b827a839"
account_actions = "0x1e04afce2c728679d58d32fbb44063eb0d85fbba1d9e75976d800e3b325beee2"
