[package]
name = "futarchy_governance_actions"
edition = "2024.beta"
published-at  = "0x0"

[dependencies]
AccountProtocol = { local = "../move-framework/packages/protocol" }
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }
futarchy_markets_primitives = { local = "../futarchy_markets_primitives" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_operations = { local = "../futarchy_markets_operations" }
# futarchy_lifecycle = { local = "../futarchy_dissolution_actions" } # Circular dependency removed
futarchy_factory = { local = "../futarchy_factory" }
[addresses]
futarchy_governance_actions = "0xd6c103021c31d6057901f22f2d32298f166a4a5b5bbf2a13d1227ace58a0b8b2"
futarchy_one_shot_utils = "0x487c17c6778ed34664b02a3d74b43e4ebc06f8185398c4d8234344ea9a536a6b"
futarchy_types = "0xbdbdfdd75fab3265eb1857820f70105208d08fb77cbe80b55fe20209871e0fa1"
futarchy_core = "0x38e7547c0387dabdc8ee889ce91e9923b245a56b20437525e91f3b89e9ac4074"
futarchy_markets_primitives = "0x724a132d4d6c25cc197550d7317804f93e34b31c8094e3307ef46b71b7434197"
futarchy_markets_core = "0xe6dd72eaa5d0c60152449f6a28f8dfa04cc412e1606bfbc76a89b54eb2633328"
futarchy_markets_operations = "0x631fdabeb831d03f27389e63b8a0ba99b20910f8334158d88c26b56de46ea2cb"
# futarchy_lifecycle  = "0x0" # Circular dependency removed
futarchy_factory = "0x5c7c22836be63e6d62e1999f38eb9ca85f565a4a03f358fcbbca87e073b40952"
account_protocol = "0xa40279af5a24bb499b137de6a8d0b91fe42d8965ad9a7a7c3fab221b73c273a0"
