[package]
name = "futarchy_governance_actions"
edition = "2024.beta"
published-at  = "0x0"

[dependencies]
AccountProtocol = { local = "../move-framework/packages/protocol" }
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }
futarchy_markets_primitives = { local = "../futarchy_markets_primitives" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_operations = { local = "../futarchy_markets_operations" }
# futarchy_lifecycle = { local = "../futarchy_dissolution_actions" } # Circular dependency removed
futarchy_factory = { local = "../futarchy_factory" }
[addresses]
futarchy_governance_actions = "0x5895d0487ed25c13f89485eb824325e8c5b3821a5869a2bb6f75d18498f413a3"
futarchy_one_shot_utils = "0xdd1191868db96df955097c80f87e0f9fad810a9fc1a31eaad40a6ebd252b498c"
futarchy_types = "0xe2af2efc7f178e604d6fb92ed8370dbddf5a9ece6b8efad5d54466704a6199ae"
futarchy_core = "0x0460272744b14feedbda6381d8745dda5a56dc3b8c0fb26fb2d35d708e1ff203"
futarchy_markets_primitives = "0xa0c8953fe904beeda00478e69304ae760dd8383d254ab6ad3b74d35588b6122b"
futarchy_markets_core = "0xa77a01c8d4bcb47d3faebf711ea077992056f58c0b45ec82058dbb0e236022ce"
futarchy_markets_operations = "0x33492d673a9b55b8451cdaeda89887496a18c6a3f463a8cf8381c5f72c5100c4"
# futarchy_lifecycle  = "0x0" # Circular dependency removed
futarchy_factory = "0x5ad012e96e5f18070350b0b6a810297505ee3d05d7ac8d86d2228e3f93e75b5b"
account_protocol = "0x59f8a732060ff3782160c08b3e463831ad772c4d8adc6e90f4e768106daf1d0f"
