[package]
name = "futarchy_governance_actions"
edition = "2024.beta"
published-at  = "0x0"

[dependencies]
AccountProtocol = { local = "../move-framework/packages/protocol" }
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }
futarchy_markets_primitives = { local = "../futarchy_markets_primitives" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_operations = { local = "../futarchy_markets_operations" }
# futarchy_lifecycle = { local = "../futarchy_dissolution_actions" } # Circular dependency removed
futarchy_factory = { local = "../futarchy_factory" }
[addresses]
futarchy_governance_actions = "0xd988781e4d97031cb5afb60c5ff3fb33a26db9cc85e431b7a7ccf3aefbaa2d4d"
futarchy_one_shot_utils = "0x50b2f371440ccf0ab9a2fdbdb1c8f34895e99dec3f0521dba39c95ee55587ace"
futarchy_types = "0x3d39d32345b3d0b5a617f35fce06daa72228ff236c7e21d0620d700be571effa"
futarchy_core = "0xc21817fa0e2eb088a54658a1b79dd733ec3d1fe9a80c3407c2f14628eda5bd83"
futarchy_markets_primitives = "0x778d27cafe0a84a44693deede9dbce81421c58e0f51506071df59f6769a5bed5"
futarchy_markets_core = "0x62ba607091a15a19f1fa72c29e90e82d96d1378b9d9ac05ba79da32dda2d6b16"
futarchy_markets_operations = "0x6b24758db9fb9608e712c3785ab9af5707c0fc0bd4158debfd336496dd0949c7"
# futarchy_lifecycle  = "0x0" # Circular dependency removed
futarchy_factory = "0x6ec29f1daff1d88f113970f6dfd7a4adf68bf37c7e0f708c6efbe68e0807728e"
account_protocol = "0xdec1aefcb32ccca2bf14635b3a8b7787c028ea9c3c3df2211ad49bf13afcb16f"
