[package]
name = "futarchy_governance_actions"
edition = "2024.beta"
published-at  = "0x0"

[dependencies]
AccountProtocol = { local = "../move-framework/packages/protocol" }
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }
futarchy_markets_primitives = { local = "../futarchy_markets_primitives" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_operations = { local = "../futarchy_markets_operations" }
# futarchy_lifecycle = { local = "../futarchy_dissolution_actions" } # Circular dependency removed
futarchy_factory = { local = "../futarchy_factory" }
[addresses]
futarchy_governance_actions = "0x4730d49e2b0b6e8e637d4d82402177ae025909a75bc028a8fd652b82fe519a69"
futarchy_one_shot_utils = "0x32841cbc60b75874bcafd94e3aad34cdaa80805b662ce5b79d83daa3d5f8df3a"
futarchy_types = "0x926bc9c6504a2b1fa288f13efccd5b3e25caff89f982c8185d77f4d60078bbc4"
futarchy_core = "0xee6fd24c69815b8a4740e1f0de1f60ae1a07517e0ddd936695ca72302197a680"
futarchy_markets_primitives = "0xabde512465e9c6303a1adc083adbadd3c45526b70059c857ac46e3f160a2642a"
futarchy_markets_core = "0xf19d6dda333f3b73f36e4ccf4057487a6b3caa3ea83c564b71cb10ec8ca57f9c"
futarchy_markets_operations = "0x1b3c2c6379de0b9bd28c8b4e26108a45bbd613386b84c500fa5c1f41faf58a36"
# futarchy_lifecycle  = "0x0" # Circular dependency removed
futarchy_factory = "0x3b9207d4550e0ea90a7b53854d68fe75bda85a7d7fd805d1a7b0efc9c3510591"
account_protocol = "0xb0026b60f2035cb8bfb3a746ebb1c6af9bd037207ee9ea3123dcfec805f19ea1"
