[package]
name = "futarchy_governance_actions"
edition = "2024.beta"
published-at  = "0x0"

[dependencies]
AccountProtocol = { local = "../move-framework/packages/protocol" }
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }
futarchy_markets_primitives = { local = "../futarchy_markets_primitives" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_operations = { local = "../futarchy_markets_operations" }
# futarchy_lifecycle = { local = "../futarchy_dissolution_actions" } # Circular dependency removed
futarchy_factory = { local = "../futarchy_factory" }
[addresses]
futarchy_governance_actions = "0xe3408f59fda9293e7a51942bded3bbd8ef033317d96e055ab12be558a31d2b1a"
futarchy_one_shot_utils = "0x247d3ea9965e8e7355de67d90e17fbde5aef05900faae2f2c1b9a142c4d7045d"
futarchy_types = "0x99961ed06ee6dc916a607a69c7ad5a0bfff0f914d77a952e925060c517958fa5"
futarchy_core = "0x5fe5878b785a4b28cb5414e94d545014a0b0484b88b989f98361acf808f848f8"
futarchy_markets_primitives = "0x1cc4fcdc30b6e7240be2278b4b73556af8700140d543aec4d1d1e87b1a954e60"
futarchy_markets_core = "0xd3a6de86f787713325b3c0998f10e61165a4e6a021abac0aeefd983e6f9d8398"
futarchy_markets_operations = "0x14fa616700f8b481992cb688fb019d21e82532803d0e2465c724ac67b97c1483"
# futarchy_lifecycle  = "0x0" # Circular dependency removed
futarchy_factory = "0xd446c8e05cf5bb49f9470b7a039980325932914597c0069c92fc7ce6800f0400"
account_protocol = "0x2fbef131639a2febdd72814533faff704b8d42b1c1f37cd4a27ad725a4e6eff3"
