[package]
name = "futarchy_governance_actions"
edition = "2024.beta"
published-at  = "0x0"

[dependencies]
AccountProtocol = { local = "../move-framework/packages/protocol" }
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }
futarchy_markets_primitives = { local = "../futarchy_markets_primitives" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_operations = { local = "../futarchy_markets_operations" }
# futarchy_lifecycle = { local = "../futarchy_dissolution_actions" } # Circular dependency removed
futarchy_factory = { local = "../futarchy_factory" }
[addresses]
futarchy_governance_actions = "0xbb10f4a13f1959fb74343225a71cb9b30b261e284f2c3f32641394946e34fb36"
futarchy_one_shot_utils = "0x40c68c25eedceca27bfdf3bb5e25300c3c1d75ec3c8eff809e896d38e5c2aa1b"
futarchy_types = "0x80ecc04c6374cb318c4166b3a2802d45d31a82773f82e8533a8eedb943d8681f"
futarchy_core = "0xcf84743109ec866c41e9659efc1c1b14582cc566255054455c97cd9d98e6bd0d"
futarchy_markets_primitives = "0x30b540d5e013c613d7d01c9ee43800358afd7866b98672edce334a3cedee4981"
futarchy_markets_core = "0xa8448615cbe5c62a931ccaf2634750f58b31de079e23e5eccb1d5663cc39469f"
futarchy_markets_operations = "0x6dfaeba5ba98c8ca8cb35935a7201854ca652e3866c8ee34e3bdc1ca8335f7ae"
# futarchy_lifecycle  = "0x0" # Circular dependency removed
futarchy_factory = "0x0858676b3a64d150eb1c2f466ce91aec30c1048e621873ff208bdc90af181306"
account_protocol = "0x54d93527a2e54cc8d7a5012496eb0080d1d373b8a4ba05fd2637d21ed5bd29ae"
