[package]
name = "futarchy_markets_primitives"
edition = "2024"
license = "BSL"

[dependencies]
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }

[addresses]
futarchy_markets_primitives = "0x778d27cafe0a84a44693deede9dbce81421c58e0f51506071df59f6769a5bed5"
futarchy_types = "0x3d39d32345b3d0b5a617f35fce06daa72228ff236c7e21d0620d700be571effa"
futarchy_one_shot_utils = "0x50b2f371440ccf0ab9a2fdbdb1c8f34895e99dec3f0521dba39c95ee55587ace"
futarchy_core = "0xc21817fa0e2eb088a54658a1b79dd733ec3d1fe9a80c3407c2f14628eda5bd83"
account_protocol = "0xdec1aefcb32ccca2bf14635b3a8b7787c028ea9c3c3df2211ad49bf13afcb16f"
account_actions = "0x08f6f38e82f5238dd3a824cfad4c5da32bae3d6b0b85434bc44ee52089881c5f"
