[package]
name = "futarchy_markets_primitives"
edition = "2024"
license = "BSL"

[dependencies]
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }

[addresses]
futarchy_markets_primitives = "0x94a46e6eabf16df7c51fbf2f88486d20859df0d71a46a482c61c75c485792cf8"
futarchy_types = "0xa06cb418b560633850b1f87cd427a39f07af1c90450fedf9eafc9dbe302175e8"
futarchy_one_shot_utils = "0x18bacc6c12bb87f6c2ea5048081d9ee0aa7e8307e727225593e2d1fe2ede93f5"
futarchy_core = "0xfc510a880a9264679b125916302f9f266694f544275d55eeec624b70a0eef4a8"
account_protocol = "0x1af6547488aa54a85b7702c21e2bba46e122baf7aa2f9e57a18456fb21731fc9"
account_actions = "0xdc54c60d24003ce93b8fbc41c8cd8b92a41b9a82d4c1ed893a0eda57ea313eae"
