[package]
name = "futarchy_one_shot_utils"
edition = "2024"
license = "BSL"

[dependencies]

[addresses]
futarchy_one_shot_utils = "0x4112eceed4a46cb27a74c60004e52992fe8d0a7cf0b5ffdf0be4ffa8147e1fdd"
