[package]
name = "futarchy_one_shot_utils"
edition = "2024"
license = "BSL"

[dependencies]

[addresses]
futarchy_one_shot_utils = "0x71a6037c0b7b8129f609bf75b59224543f404a1f2cee377524d5a9dc49d050c5"
